root = "/app"
tmp_dir = "tmp"

[build]
cmd = "go build -o sls"
bin = "sls"
full_bin = "./sls"
include_ext = ["go"]
exclude_dir = []
include_dir = []
exclude_file = []
exclude_regex = []
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[misc]
clean_on_exit = true
